// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Author = Collections['author']['schema']['_output']
export declare const author: Author[]

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]
