import type { Metadata } from 'next';
import { unstable_setRequestLocale } from 'next-intl/server';
// import dynamic from "next/dynamic";
import { ReactNode } from 'react';

import Dummy from '@/components/dummy';
import { jetBrainMono, lora, openSans } from '@/configs/fonts';
import ThemeProvider from '@/providers/theme-provider';
import '@/styles/main.css';
import { Locale } from '@/types/locales';

export const metadata: Metadata = {
  title: 'MK Blog | Home',
  description: 'Generated by create next app',
};

type TLocaleLayoutProps = {
  children: ReactNode;
  params: {
    locale: Locale;
  };
};

// List of valid locales
const validLocales: Locale[] = ['en', 'vi']; // Add your valid locales here

// const Header = dynamic(() => import("@/layouts/Header"), {
//   ssr: false,
//   loading: () => <div>Loading...</div>,
// });

function LocaleLayout({
  children,
  params: { locale },
}: Readonly<TLocaleLayoutProps>) {
  // Enable static rendering
  unstable_setRequestLocale(locale);

  // Validate the locale
  if (!validLocales.includes(locale)) {
    // throw new Error(`Unknown locale encountered: "${locale}".`);
    return null;
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${openSans.variable} ${lora.variable} ${jetBrainMono.variable}`}
      >
        <ThemeProvider>
          {children}
          <Dummy />
        </ThemeProvider>

        <a href="/asd">hehe</a>
        <div style={{ height: 2000 }} />
      </body>
    </html>
  );
}

export default LocaleLayout;
